### ISSUE TITLE
YouTube profile verification

### ISSUE THREAD

**Issue by mradkov** [aeternity/tipping-oracle-service#21]
The parsing script should be improved to match also youtube profiles the same way as we did for twitter.

**Comment by thepiwo** [comment]
It's not possible "the same way" as for twitter, there needs to be some new logic. In twitter each tweet url is `user/id`, we choose the user, youtube videos don't have this.

The parser will have to be more complex to find the username, then go to thats user profile about page.

**Comment by mradkov** [comment]
I mean the **same flow** -> where the content creator has to only verify their profile and then the oracle can check the creator of the tipped video and match the address in the profile 💭

**Comment by thepiwo** [comment]
sure, thats doable

**Comment by thepiwo** [comment]
Keep in mind, what you described is not the actual flow. There is no "verified profile". We do indentify a twitter url, if that page doesn't contain the expected public key, we do open the distinct profile url and only check the bio box.

**Comment by mradkov** [comment]
We should prevent the oracle from looking into the comment section though (for YT) 🤔
